name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: 'windows'
          - os: macos-latest
            label: 'macos-arm'
          - os: macos-13
            label: 'macos-x86'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: Setup msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain zip
          path-type: inherit

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne package
          zip -r FileHasher-Windows-x86_64.zip File\ Hasher.exe
        shell: msys2 {0}

      - name: Build for macOS ARM
        if: matrix.label == 'macos-arm'
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne package
          zip -r FileHasher_macOS_aarch64.zip ./File\ Hasher.app

      - name: Build for macOS x86
        if: matrix.label == 'macos-x86'
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          fyne package
          zip -r FileHasher_macOS_x86_64.zip ./File\ Hasher.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.label }}
          path: |
            FileHasher_macOS_aarch64.zip
            FileHasher_macOS_x86_64.zip
            FileHasher-Windows-x86_64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            FileHasher_macOS_aarch64.zip
            FileHasher_macOS_x86_64.zip
            FileHasher-Windows-x86_64.zip
